AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Architectures: x86_64
    Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
    Environment:
      Variables:
        PORTFOLIO_DATABASE_PATH: !Ref PORTFOLIO_DATABASE_PATH
        PORTFOLIO_DATABASE_NAME: !Ref PORTFOLIO_DATABASE_NAME

Resources:
  PortfolioReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      # PackageType: Image
      Architectures:
        - x86_64
      CodeUri: src
      Handler: app.handler
      Runtime: python3.12
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
          # Cors:
          #   AllowMethods: "'*'"
          #   AllowHeaders: "'*'"
          #   AllowOrigin: "'*'"
  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'